name: docker
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Packages V2
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username doxa-labs --password-stdin

      - uses: actions/checkout@master

      - name: Build the Docker Image
        run: docker build . --file Dockerfile --tag ghcr.io/doxa-labs/docker-helloworld/docker-helloworld:latest

      - name: Push to GitHub Registry
        run: docker push ghcr.io/doxa-labs/docker-helloworld/docker-helloworld:latest

      - name: Logout
        run: docker logout
